trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: globalVariable
  value: "this is root level variable"
- name: overrideGlobalVariable
  value: "Root"
- name: overrideGlobalandStageVariable
  value: "Global"

stages:
- stage: 
  displayName: "Stage 1"
  variables:
    stageVariable: "This is Stage 1 level variable"
    overrideGlobalVariable: "Stage 1"
    overrideGlobalandStageVariable: "Stage 1"

  jobs:
  - job: BuildAndTest
    variables: 
     - name: jobVariable
       value: "This is job level variable in stage 1"
     - name: overrideGlobalandStageVariable
       value: "job"

    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 
          echo ${{ variables.sameNameVariable }}
          echo "Globa Variable :" $(globalVariable)
          echo "stageVariable :" $(stageVariable) 
          echo "jobVariable :" $(jobVariable)
          echo "jobVariable :" $(overrideGlobalVariable)
          echo "jobVariable :" $(overrideGlobalandStageVariable)

